name: Build
on:
  push:
    branches:
      - "**"

permissions:
  id-token: write # needed for depot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Create Docker tags and metadata for the API
        id: api-meta
        uses: docker/metadata-action@v5
        with:
          bake-target: "api-meta"
          images: |
            wito3030/nano-grpc
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 7

      - name: Build
        uses: depot/bake-action@2a7b3650f132c787714b9f582dc74e154faad669
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.api-meta.outputs.bake-file }}
          targets: default
          provenance: mode=max
          sbom: true
          push: false # testing only
          save: true
